awsAccountId: '579742570368'
awsRegion: 'us-east-2'

vpcCidr: '10.0.0.0/16'
natGatewaysCount: 1

vpcSsmParam: '/dev/app-vpc-id'
defaultEcsExecRoleSsmParam: '/dev/ecs-default-execution-role'
defaultEcsTaskRoleSsmParam: '/dev/ecs-default-task-role'
albArnSsmParam: '/dev/alb-arn'
albSecurityGroupSsmParam: '/dev/alb-sg-id'
ecsClusterName: 'dev-cluster'

dbCredentialSecret: 'dev/db/credentials'
dbPublicAccess: true

databaseApi:
  containerPort: 8101
  hostPort: 8101
  serviceName: 'databaseApi'
  dockerImageUrl: 'etenlab/database-api'
  cpu: 512
  memory: 1024
  taskCount: 1

adminApi:
  containerPort: 8101
  hostPort: 8101
  serviceName: 'adminApi'
  dockerImageUrl: 'etenlab/admin-api'
  cpu: 512
  memory: 1024
  taskCount: 2
