awsAccountId: '579742570368'
awsRegion: 'us-east-2'

vpcCidr: '10.0.0.0/16'
natGatewaysCount: 0

vpcSsmParam: '/dev/app-vpc-id'
defaultEcsExecRoleSsmParam: '/dev/ecs-default-execution-role'
defaultEcsTaskRoleSsmParam: '/dev/ecs-default-task-role'
albArnSsmParam: '/dev/alb-arn'
albSecurityGroupSsmParam: '/dev/alb-sg-id'
ecsClusterName: 'dev-cluster'

dbCredential: 'dev/db/password'

databaseApi:
  containerPort: 8101
  hostPort: 8101
  serviceName: 'databaseApi'
  dockerImageUrl: 'docker.io/etenlab/database-api:latest'
  cpu: 512
  memory: 1024
  taskCount: 1

adminApi:
  containerPort: 8101
  hostPort: 8101
  serviceName: 'adminApi'
  dockerImageUrl: 'etenlab/admin-api:latest'
  cpu: 512
  memory: 1024
  taskCount: 2
