# AWS env settings
awsAccountId: '579742570368'
awsRegion: 'us-east-2'

# Prefix used to identify app CloudFormation component
appPrefix: 'cb'

# VPC configuration
vpcCidr: '10.10.0.0/16'
natGatewaysCount: 0

# Env domain setup
createEnvHostedZone: false # set to "true" if you want to create envDomainName, i.e."prod.crowd.bible"
rootDomainName: 'crowd.bible'
rootDomainCertArn: 'arn:aws:acm:us-east-2:579742570368:certificate/000000000' # required if createEnvHostedZone is "false"

# App ECS cluster name
ecsClusterName: 'prod-cluster'

# System Manager params to create
vpcSsmParam: '/prod/app-vpc-id'
defaultEcsExecRoleSsmParam: '/prod/ecs-default-execution-role'
defaultEcsTaskRoleSsmParam: '/prod/ecs-default-task-role'
albArnSsmParam: '/prod/alb-arn'
albSecurityGroupSsmParam: '/prod/alb-sg-id'
dbSecurityGroupSsmParam: '/prod/db-sg-id'
domainCertSsmParam: '/prod/root-domain-certificate'

# Secrets Manager params to create
dbCredentialSecret: 'prod/db/credentials'

# Whether database is accessible outside of VPC
dbPublicAccess: false

# Config for frontend showcase app
showcaseApp:
  domainName: 'showcase.crowd.bible'

# Config for database API app
databaseApi:
  dockerPort: 8101
  albPort: 3001
  subdomain: 'db'
  serviceName: 'databaseApi'
  dockerImageUrl: 'etenlab/database-api'
  cpu: 512
  memory: 1024
  taskCount: 1
  priority: 10
  environment:
    - PORT: 8101
    - RUN_MIGRATIONS: false

# Config for admin API app
adminApi:
  dockerPort: 8101
  albPort: 3002
  subdomain: 'admin'
  serviceName: 'adminApi'
  dockerImageUrl: 'etenlab/admin-api'
  cpu: 512
  memory: 1024
  taskCount: 2
  priority: 20
  environment:
    - PORT: 8101
    - RUN_MIGRATIONS: false
